# Generated by Django 5.2.3 on 2025-07-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_amenity_hotel_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
